// AUTO-GENERATED by scripts/build-media.mjs. Do not edit by hand.
// Re-run `node scripts/build-media.mjs` after adding source photos or videos.
// Alt text lives in src/data/mediaCaptions.ts so it survives regeneration.

// Name every asset, so referencing a missing id fails to compile.
// Splitting photos from clips lets a video-only slot reject a photo id at compile time.
export type ImageId =
  | 'img-3051'
  | 'img-3053'
  | 'img-3052'
  | 'img-3050'
  | 'img-3049'
  | 'img-3048'
  | 'img-3047'
  | 'img-3046'
  | 'img-3045'
  | 'img-3022'
  | 'img-3028'
  | 'img-3011'
  | 'img-3010'
  | 'img-2997'
  | 'img-2994'
  | 'img-2948'
  | 'img-2947'
  | 'img-2946'
  | 'img-2874'
  | 'img-2856'
  | 'img-2869'
  | 'img-2842'
  | 'img-2790'
  | 'img-2790-1'
  | 'img-2789'
  | 'img-2631'
  | 'img-2764'
  | 'img-2597'
  | 'img-2508'
  | 'img-2527'
  | 'img-2528'
  | 'img-2536'
  | 'img-2755'
  | 'img-2756'
  | 'img-2758'
  | 'img-2762'
  | 'img-2260'
  | 'img-2263'
  | '9db1db65-d711-44fa-8f16-dc2b6d27e097'
  | 'img-1573'
  | 'img-1572'
  | 'img-1571'
  | 'img-1570'
  | 'img-1569'
  | 'img-1568'
  | 'img-1567'
  | 'img-1566'
  | 'img-1565'
  | 'img-1165'
  | 'img-1173'
  | 'img-1172'
  | 'img-1163'
  | 'img-1164'
  | 'img-1162'
  | 'img-0320'
  | 'img-0963'
  | 'img-0964'
  | 'img-1030'
  | 'img-1047'
  | 'img-1048'
  | 'img-1292'
  | 'img-1418'
  | 'img-1419'
  | 'img-1420'
  | 'img-1433'
  | 'img-1433-1'
  | 'img-1432'
  | 'img-1442'
  | 'img-1438'
  | 'img-1434'
  | 'img-1479'
  | 'img-1484'
  | 'bceeb212-6993-44ef-9966-eea63b306cc4'
  | '7e9cf6f1-bf67-4cd1-ae08-1ca97711f35b'
  | 'a6816173-c39d-4a76-8d7c-b76816696070'
  | '62e190ee-638b-4cc4-8307-dc54044596d6'
  | 'img-2044'
  | 'img-2110'
  | 'img-2118'
  | 'img-2264'
  | 'img-2312'
  | 'img-2374'
  | 'img-2373'
  | 'img-2382'
  | '490754b5-69ae-4ae0-a545-d0f714170e2d'
  | 'df5fce9f-3232-4d2d-a1cc-c61f507de491'
  | 'a6b5217c-219e-4090-9d77-68a82cbe85a5'
  | 'img-2387'
  | 'img-2386'
  | 'img-2964'
  | 'img-2797'
  | 'img-2798'
  | 'img-2968'
  | '2530172260126415111'
  | '3914887227531153922'
  | '8454996906743694765'
  | '718490688518547100'
  | '9173955381485114153'
  | '7263495715122942951'
  | '7263495715122942951-jpg-1'
  | '7370407339484804058'
  | '7708165599640676557'
  | '1976410277356390327'
  | '955498783347505657'
  | '7306127883356801794'
  | '4598324176699077351'
  | '3511554821892522494'
  | '1694422870994021925'
  | '3531799507795455560'
  | '4349539558343909612'
  | '2385689756380270605'
  | '941607886375482599'
  | '8404362930630178800';

export type VideoId =
  | 'video-2025-08-29-11-15-10'
  | 'renderedvideo'
  | '6ad5d647-3611-4873-9fcd-50465ef97b9e'
  | 'a0673548-59dd-42ca-9122-30a9bb45a3dc'
  | 'img-2414'
  | 'img-2434'
  | '833465387477952285'
  | '5453990239390041725'
  | '2014366607164268207'
  | '1102936990649038933'
  | '2195008587047542519'
  | '1390147046224996442'
  | '4039484844690051570';

export type MediaId = ImageId | VideoId;

export type MediaOrientation = 'landscape' | 'portrait' | 'square';

type MediaBase = {
  src: string;
  width: number;
  height: number;
  orientation: MediaOrientation;
  blurDataUrl: string;
};

export type ImageMedia = MediaBase & {
  kind: 'image';
  id: ImageId;
};

export type VideoMedia = MediaBase & {
  kind: 'video';
  id: VideoId;
  /** Stand in for the clip until it plays, and serve as its grid thumbnail. */
  poster: string;
  /** Run for this many whole seconds. */
  duration: number;
};

export type MediaItem = ImageMedia | VideoMedia;

export const MEDIA: readonly MediaItem[] = [
  {
    id: 'img-3051',
    kind: 'image',
    src: '/media/photos/img-3051.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoMAAkAA4BaJYwC7ADbRN6mAAD+h9WbQAnjaWzWjKsKew4HiYTPtP65XTkfhNaq0iTM6zJ3lwJzTRZIuxglAAAA',
  },
  {
    id: 'img-3053',
    kind: 'image',
    src: '/media/photos/img-3053.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoMAAkAA4BaJZQAAp+1zJDAAP6PpSoq3Y7qx/zxcyNQH3WUpdIPqPJaMkh3cEXwJvkJukOzQgA=',
  },
  {
    id: 'img-3052',
    kind: 'image',
    src: '/media/photos/img-3052.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoMAAkAA4BaJZwAAlxk2Z3jAAD8d5hPvk1Bs8+hWR2IEfp53DEDmCnGcVOHK/0AhCCm4iGltLOEIAAIwAA=',
  },
  {
    id: 'img-3050',
    kind: 'image',
    src: '/media/photos/img-3050.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACQAQCdASoMAAkAA4BaJZwAAptwZoAA/rI5iogSUom1cUI8zzjwUQMiqfVamoOJ+VwMWBuZ7tAAD7pAAAA=',
  },
  {
    id: 'img-3049',
    kind: 'image',
    src: '/media/photos/img-3049.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoMAAkAA4BaJZQAAu0Zu4AWwAD+wAUsApNdNdHG1ST4fVnzpwXX5VWDdq6vVpG1hAA=',
  },
  {
    id: 'img-3048',
    kind: 'image',
    src: '/media/photos/img-3048.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoMAAkAA4BaJZwAAvwd7yX0QAAA/sD7bmx276xpmiLv2B+2jFMDD86lOAj5S+Us6rYZZPmHbE0wAA==',
  },
  {
    id: 'img-3047',
    kind: 'image',
    src: '/media/photos/img-3047.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoMAAkAA4BaJZwCsO/7BXINCIAA/t2B1dqYr6NfuuvcJFGYLJULIfvG882OCXeJ10quY7UBIAAAAA==',
  },
  {
    id: 'img-3046',
    kind: 'image',
    src: '/media/photos/img-3046.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoMAAkAA4BaJZwAAmi/FUrUAAD5XhNpvQtB093E5rn6JVgRAfPcS7bjSCbLq7wCH0I8HwAA',
  },
  {
    id: 'img-3045',
    kind: 'image',
    src: '/media/photos/img-3045.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACQAQCdASoMAAkAA4BaJZwAApdBo4AA/drE1AJHvTG5YQhizDwTkPFb0BW70PSnY+a24Z27VXjucBvUAAA=',
  },
  {
    id: 'video-2025-08-29-11-15-10',
    kind: 'video',
    src: '/media/videos/video-2025-08-29-11-15-10.mp4',
    poster: '/media/videos/video-2025-08-29-11-15-10.webp',
    width: 1280,
    height: 720,
    duration: 40,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADwAQCdASoMAAcAA4BaJZwAAp/hisRf4oAA99DM11xP3MdYpIubVz6GgugJ2AsrmmiL/5pP41/iM7AxQAA=',
  },
  {
    id: 'img-3022',
    kind: 'image',
    src: '/media/photos/img-3022.webp',
    width: 450,
    height: 600,
    orientation: 'portrait',
    blurDataUrl:
      'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAAAQAgCdASoJAAwAA4BaJZQCdAEWUB18/u2wAP6Xa7/aHCc/YfnRn2eEtbZIjLPMzOdWCkCBFtSX5+r4kAA=',
  },
  {
    id: 'img-3028',
    kind: 'image',
    src: '/media/photos/img-3028.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADwAQCdASoMAAkAA4BaJZwC7AEfU/wJDAAA/pFju6UmLg0FBBl7sIaWYrljV3/vEd0Rbr6wAAA=',
  },
  {
    id: 'img-3011',
    kind: 'image',
    src: '/media/photos/img-3011.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoMAAkAA4BaJZACdADbr9itpgAA4nmJfjso/HqulPaxF9K8tmUrZU4VERR0oMy8UbrfDlFqLAIyB+5rhcqjQAAA',
  },
  {
    id: 'img-3010',
    kind: 'image',
    src: '/media/photos/img-3010.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoMAAkAA4BaJYgCdIExGZoNQTzwAPljB1BiLXAKIJr7DreosNApYk8ZjIGLDj8oAHjRTY6K7GhNa0itV+Abj9lqiAAAAA==',
  },
  {
    id: 'img-2997',
    kind: 'image',
    src: '/media/photos/img-2997.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoMAAkAA4BaJZwAAsZ3J8e0AADd8tmNrUUsy3/8sg7JztuNQMNG+2/13IadwsnRd4bzyhGgAAA=',
  },
  {
    id: 'img-2994',
    kind: 'image',
    src: '/media/photos/img-2994.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoMAAkAA4BaJZwAAmitAxrQAPyxDwp2WXzOIpjlvuVicUaF+LkJYRAKIkkA9INIY70XFDa2MqNgQAAA',
  },
  {
    id: 'img-2948',
    kind: 'image',
    src: '/media/photos/img-2948.webp',
    width: 277,
    height: 600,
    orientation: 'portrait',
    blurDataUrl:
      'data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAACwAQCdASoGAAwAA4BaJZwAAuWrf7AAAP75Dm1PYgqdecf+9X8dgAAA',
  },
  {
    id: 'img-2947',
    kind: 'image',
    src: '/media/photos/img-2947.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoMAAkAA4BaJQBOgCPbDEFsZ9AA/gXiEryYD3+AnhegQxx7JaSQkHsyaFJAZ6QlrzzWklNjwIggONUYAAA=',
  },
  {
    id: 'img-2946',
    kind: 'image',
    src: '/media/photos/img-2946.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoMAAkAA4BaJZQCw7EVvGAHEAAA/gXkMK4/u+0F7ibSNeMWtl7+XhArf8BuXN4zGwwTwOuh84YlFm90iYAAAA==',
  },
  {
    id: 'img-2874',
    kind: 'image',
    src: '/media/photos/img-2874.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAQCdASoMAAkAA4BaJZQCdADYC6gAAP5rToIirKqOY2jy9jg7pgdhgplcKS/Kjxk+q6Pn2SGBEFcannj8JUZaRTgrzvS0COuwAA==',
  },
  {
    id: 'img-2856',
    kind: 'image',
    src: '/media/photos/img-2856.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoMAAkAA4BaJQBdgB0+yvIdAAD+dWFFxNKIl6e2cGm8AMUc81LnnCWtnlLxAu9HmtEVMDXesgPztLOqDflgAAAA',
  },
  {
    id: 'img-2869',
    kind: 'image',
    src: '/media/photos/img-2869.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAQAgCdASoMAAkAA4BaJZQC7AEefjJ1HQAAAPlpmhd92vOC+LScAZIfkzVmpiyxufKva+fxDI2iSU4VsR/49gqCl5vfAAAA',
  },
  {
    id: 'img-2842',
    kind: 'image',
    src: '/media/photos/img-2842.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACQAQCdASoMAAkAA4BaJQBWABqxDAAA/rsbt3Ashg+/3wNAvrtfvassq7L9QT5UJJrmcbQjPasL1TbULOT5OquaaZcgAA==',
  },
  {
    id: 'img-2790',
    kind: 'image',
    src: '/media/photos/img-2790.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoMAAkAA4BaJQBdgCPqPTgzqAAA/sIUGKIXJIN0dCsxWoS0r17wWYDlmyshNVcknU2+TvSb+LAAAA==',
  },
  {
    id: 'img-2790-1',
    kind: 'image',
    src: '/media/photos/img-2790-1.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoMAAkAA4BaJQBdgCPqPTgzqAAA/sIUGKIXJIN0dCsxWoS0r17wWYDlmyshNVcknU2+TvSb+LAAAA==',
  },
  {
    id: 'img-2789',
    kind: 'image',
    src: '/media/photos/img-2789.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoMAAkAA4BaJYwC7ADYC1QAAP5n2A1tzlqN6U7g+2AwwkAXu8kMLBt4dLwPHNRKyiHcrWZwAAA=',
  },
  {
    id: 'img-2631',
    kind: 'image',
    src: '/media/photos/img-2631.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAAAQAgCdASoMAAkAA4BaJQBdgCPX1B55xaEAAM4xnzcD/qRCaQfIemWAOEeuah1f8CXFvKi1gN/YT4o+oKiGjQAA',
  },
  {
    id: 'img-2764',
    kind: 'image',
    src: '/media/photos/img-2764.webp',
    width: 450,
    height: 600,
    orientation: 'portrait',
    blurDataUrl:
      'data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACQAQCdASoJAAwAA4BaJYwAAmcqI2AA/pgKD//si8vWLNvC77tEWkhr2MtiBHxmLu0qU1An3fGU+cqGwAAAAA==',
  },
  {
    id: 'renderedvideo',
    kind: 'video',
    src: '/media/videos/renderedvideo.mp4',
    poster: '/media/videos/renderedvideo.webp',
    width: 720,
    height: 1280,
    duration: 15,
    orientation: 'portrait',
    blurDataUrl:
      'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAQCdASoHAAwAA4BaJZwAApzjxzAAAPavfyCub1/Sgo08RF7bvtbBPn9wXNqyMQ4Ja2vo+zZagAAA',
  },
  {
    id: 'img-2597',
    kind: 'image',
    src: '/media/photos/img-2597.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACQAQCdASoMAAkAA4BaJQAARLJtLQAA/thQJ0dy4Rc9IbK7ZeAKq+rN9AixW5ZcIsJFJAu6uZcVcO+FFu+IZatriW9ef/Pc7AgAAA==',
  },
  {
    id: 'img-2508',
    kind: 'image',
    src: '/media/photos/img-2508.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoMAAkAA4BaJYwAAq9c6Ll/QAD+1hfETu7oQCHar931MCCiFW1KcaTweXZhaIhrzmv6UimRU47wYXH+qvQAAA==',
  },
  {
    id: 'img-2527',
    kind: 'image',
    src: '/media/photos/img-2527.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAAAQAgCdASoMAAkAA4BaJYwC7AEXaicGRBYAAPR0FArU2ljHjVS/tuGH8UWtZA0iTn1K2GlXgtGBrn/LAaAAAA==',
  },
  {
    id: 'img-2528',
    kind: 'image',
    src: '/media/photos/img-2528.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoMAAkAA4BaJYwCdAECwSOvrgAAzgxj4g2svp/1uR5jeAAsva/7dJkr3aYnGFL5dWY5of593XQHugAA',
  },
  {
    id: 'img-2536',
    kind: 'image',
    src: '/media/photos/img-2536.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAQAgCdASoMAAkAA4BaJZQC7AEQzUjWO2jgAP7HZah6u1TXTgOjqtFQuw0c0m5t8cgTDkZV+7mOp7qtdhlvX0DOAAk6siSgAAA=',
  },
  {
    id: 'img-2755',
    kind: 'image',
    src: '/media/photos/img-2755.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAABQAgCdASoMAAkAA4BaJYgCdH8AGOq3dVK+8XAA/u3ZMA2dOYvICKWKsq5u3hKB6m7eUpGb/yCZUBI+wjXhCyTH0/LEf9s/GEHMgMygAAA=',
  },
  {
    id: 'img-2756',
    kind: 'image',
    src: '/media/photos/img-2756.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACwAQCdASoMAAkAA4BaJZwAAevlY8hAAP3bQKxdBLi7L2UW8LVtlZKDWfgQghzAXrcUpAAA',
  },
  {
    id: 'img-2758',
    kind: 'image',
    src: '/media/photos/img-2758.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAQCdASoMAAkAA4BaJZQAAvo2lbt5oAD+SbsHNVPb9FeTbPFGPwxZ5jIT5Je4Tfh8SWIIbLZRfu71SHAAAA==',
  },
  {
    id: 'img-2762',
    kind: 'image',
    src: '/media/photos/img-2762.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoMAAkAA4BaJQBOgCBvNOx/AAD5QSicti/oR9xCKNDSy/Pg8ivbaLO8lRYP2/FgmyekSfwZtqwl7XGVkFiUAAAA',
  },
  {
    id: 'img-2260',
    kind: 'image',
    src: '/media/photos/img-2260.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACQAQCdASoMAAkAA4BaJYwAAlJUEkAA+VKSgw1duSLGdkNTwETUAJ/7YbCc7wEdHOZHkBqOdfkdwsoA',
  },
  {
    id: 'img-2263',
    kind: 'image',
    src: '/media/photos/img-2263.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoMAAkAA4BaJZQAAlodq/+28AD9+Gqh6i/Ru3WteCVOTPtYbk5DB5JFyJaL9DVxQAKrZrDX42oBbxLwAAA=',
  },
  {
    id: '9db1db65-d711-44fa-8f16-dc2b6d27e097',
    kind: 'image',
    src: '/media/photos/9db1db65-d711-44fa-8f16-dc2b6d27e097.webp',
    width: 450,
    height: 600,
    orientation: 'portrait',
    blurDataUrl:
      'data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAQCdASoJAAwAA4BaJZQC7ADdDjIAQAD8j7+mqt35GIqoqiwsbB+aHoPiLJ0UuLX4tR09F5WfXTdiF8SP8bY5ObyqVUGcnxppNIAA',
  },
  {
    id: 'img-1573',
    kind: 'image',
    src: '/media/photos/img-1573.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoMAAkAA4BaJQAATRW348vpAADiBATCAyHIow7ytJz6MyXUiPBL+wFJfeSiCwIHrWpu6PcRDgA=',
  },
  {
    id: 'img-1572',
    kind: 'image',
    src: '/media/photos/img-1572.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoMAAkAA4BaJZQAAlyu69/5oAD5bH2C326ZD6TGf1czLaL1L6o9MjWBIekyhn9/Hj/5/Uar5XAfmcE1voUAAA==',
  },
  {
    id: 'img-1571',
    kind: 'image',
    src: '/media/photos/img-1571.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoMAAkAA4BaJZQAAlqCOu+KgAD+YBnmn9UqeGQQm4dvPh+BCHwVHY/0kf23z3PhfZ5NNvmHCYbne667rqFAAA==',
  },
  {
    id: 'img-1570',
    kind: 'image',
    src: '/media/photos/img-1570.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoMAAkAA4BaJZwAAmg92akp2ygA/ImszvQ5FiVVnlvIcaLiJEvH7HiWSw27nu+tCCCNRWxZwgWYuWMFYAA=',
  },
  {
    id: 'img-1569',
    kind: 'image',
    src: '/media/photos/img-1569.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoMAAkAA4BaJZQAArL/M3Rp0AD+kPtPzbYEwRyxAV8nK54yufBM3wHGnQ7OX3sYL/Andi2GeEYTc14Bv0AAAA==',
  },
  {
    id: 'img-1568',
    kind: 'image',
    src: '/media/photos/img-1568.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACQAQCdASoMAAkAA4BaJZwAAldi5MAA/mV6L0l7m+Pzp2nTAwUpqJnZYk+Rf5rCP3+SsOUe+2ex6fNPpDUaAA==',
  },
  {
    id: 'img-1567',
    kind: 'image',
    src: '/media/photos/img-1567.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoMAAkAA4BaJZwAAmiwTzFSgADdq5fmePDoJ6TBz4BYXav376gAbVuy2ZiF7hEB5IQAAA==',
  },
  {
    id: 'img-1566',
    kind: 'image',
    src: '/media/photos/img-1566.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoMAAkAA4BaJZwAAvaeaZS9MAD+ZJYMOdohRrjFckMAnh6iA5hmF1XlxDFLYtdl+vdxeILOAXKTxvoUAAA=',
  },
  {
    id: 'img-1565',
    kind: 'image',
    src: '/media/photos/img-1565.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoMAAkAA4BaJYwAAmfeYa4dcADLS0NdwmkzQC8x7nFthWIYIypKclvYSvkrcHXSp2XU5p6yyq9UNywppFbiIcAA',
  },
  {
    id: 'img-1165',
    kind: 'image',
    src: '/media/photos/img-1165.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoMAAkAA4BaJQBWACPqSabBpAAA/uHpSi9Fn7cDWkNX0JgDfwytJ+vNjaZWs9PcMhY/rZoFRHk7jmoxpwykwAksKAAAAA==',
  },
  {
    id: 'img-1173',
    kind: 'image',
    src: '/media/photos/img-1173.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoMAAkAA4BaJZQAAlrmDakzgAD+AzU2OV5I3xEIEsnyMOCpqqZCfzBzjzxWcpohXjEEkY/AAAA=',
  },
  {
    id: 'img-1172',
    kind: 'image',
    src: '/media/photos/img-1172.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACwAQCdASoMAAkAA4BaJZQAAlrd2oJAAP6aVhme1uW2pNct+53TLRmoe8q/CuyEWRg5JalKn/oFjLZt4uAAAA==',
  },
  {
    id: 'img-1163',
    kind: 'image',
    src: '/media/photos/img-1163.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoMAAkAA4BaJYgCdAD8Lo/oo3AAAP5b0N1BEJwN3qiS+pezn5dvpefuGuMU3nCGwDRaeIDGpx7PJs4evbLBiPk7dAAAAA==',
  },
  {
    id: 'img-1164',
    kind: 'image',
    src: '/media/photos/img-1164.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoMAAkAA4BaJZgCdAEW/yHMcAAA+WKZ+m4WFsP42hXuMjlWkp/jiOuQwYHPlY4t/pQZB2vUxqy9PjIn7U7x1BTNGsG3jAAA',
  },
  {
    id: 'img-1162',
    kind: 'image',
    src: '/media/photos/img-1162.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoMAAkAA4BaJQBOgCHeqUPgVQAA8mS99QXfH5NidKvht5ViCLzDIYFHYKRmn8RualInda/Bw0VIAAAA',
  },
  {
    id: 'img-0320',
    kind: 'image',
    src: '/media/photos/img-0320.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoMAAkAA4BaJQBdgCPV05j3AADN8O/02I+r4bf3KnWQaDvdcbaPKT0k+j8fDyU2tTCouXN0DDu5QtrJLiBezgAA',
  },
  {
    id: 'img-0963',
    kind: 'image',
    src: '/media/photos/img-0963.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAQCdASoMAAkAA4BaJZQC7ADYC+sAAP5YeJJGfVVTeG1Uok47RAOZX8zsC2lTlt36mR8YAAA=',
  },
  {
    id: 'img-0964',
    kind: 'image',
    src: '/media/photos/img-0964.webp',
    width: 450,
    height: 600,
    orientation: 'portrait',
    blurDataUrl:
      'data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAAAQAgCdASoJAAwAA4BaJZQC7AEXZV6w1jgAAOJwOx/9HWX0IXtHwny2Dsl7ITa+5X0/X4wkipEJ/PrjuILTksAA',
  },
  {
    id: 'img-1030',
    kind: 'image',
    src: '/media/photos/img-1030.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACQAQCdASoMAAkAA4BaJZQAAluXfQAA9r7kHEoJNk5c1HyHtVVTi3Fe1exzXHKsUcuCYoVLnvmGvF+WAAA=',
  },
  {
    id: 'img-1047',
    kind: 'image',
    src: '/media/photos/img-1047.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAQCdASoMAAkAA4BaJYwC7ADMpRWzgAD5Zo7Rnw7GtyBDmMBX1bN4RVQYyNZERjLQ0W322yXcwidr6cIAAA==',
  },
  {
    id: 'img-1048',
    kind: 'image',
    src: '/media/photos/img-1048.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACQAQCdASoMAAkAA4BaJZQC7ADghqAA/XioTDtxfWMPbvgVNUwcOZlPWi2CmUhqNQobWWjhfU9moaSNAAA=',
  },
  {
    id: 'img-1292',
    kind: 'image',
    src: '/media/photos/img-1292.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoMAAkAA4BaJZQCw7DdIHD4AADifDFn7tn9HtUqS+XpA+V3TGhUJbWjUTzP/Bd6/L6xTZlEXHZm8p/GpMAAAA==',
  },
  {
    id: 'img-1418',
    kind: 'image',
    src: '/media/photos/img-1418.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoMAAkAA4BaJQBWAB6uLO6QYAAAzFRZEP0Qg2/ATC7BZvXUeCdd+kHQUWta15W1UWuCSZibxRaJSL+hWdlY2wwAAAA=',
  },
  {
    id: 'img-1419',
    kind: 'image',
    src: '/media/photos/img-1419.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoMAAkAA4BaJYgCw7DH0d/NAADyoZCVulSfDEX2TO598b52pPbwS5GAoASRrqCIabDBGo6FeHo87C6yIzMcseoOqAAAAA==',
  },
  {
    id: 'img-1420',
    kind: 'image',
    src: '/media/photos/img-1420.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoMAAkAA4BaJQBOgBu2hb8kroAA4DX2RX8ZSJMD67Bza7augy6LNbGaP2jY2jDvqPXCQcfQA1DZOxJdpTAAAA==',
  },
  {
    id: 'img-1433',
    kind: 'image',
    src: '/media/photos/img-1433.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACwAQCdASoMAAkAA4BaJYwCdADzHMkAAPhFMweGeMRIL5f015PmUadpKlMf7CeGR+n2npVfuN7IzxuaR/XkZ4uzA+FAk9IPAAA=',
  },
  {
    id: 'img-1433-1',
    kind: 'image',
    src: '/media/photos/img-1433-1.webp',
    width: 1920,
    height: 1440,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACwAQCdASoMAAkAA4BaJYwCdADzHMkAAPhFi2wnCRDwExITVRcvMY5JvZdtyPcwh8fAR20w/w56VPHK6OlOyYSGa6CDxNphAAA=',
  },
  {
    id: 'img-1432',
    kind: 'image',
    src: '/media/photos/img-1432.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACQAQCdASoMAAkAA4BaJQBOgB6FE4AAyjgQN9YGjO0SFcpyYfxg0p1vB8ZdcQ/+YS07ZDTL0P/fVEnhgAA=',
  },
  {
    id: 'img-1442',
    kind: 'image',
    src: '/media/photos/img-1442.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoMAAkAA4BaJYwCdADb8Y3AwADh9nY12DTEBXCOjiZUE5sB/oqQxVnNTsg6vn2YzlAEeW9wAAA=',
  },
  {
    id: 'img-1438',
    kind: 'image',
    src: '/media/photos/img-1438.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoMAAkAA4BaJQBOgB8v8pzQsAAA/ZocJjQyLiX7OnMEMTZ5ujO8ZBdrAwZbR8DuWZ9elGawtMqEUpZiQWqDt0fgIbYIeAsWIRStfoioAAA=',
  },
  {
    id: 'img-1434',
    kind: 'image',
    src: '/media/photos/img-1434.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACQAQCdASoMAAkAA4BaJQBOgBsBaoAAywq/d+HlpwwfzPFCNx3oulQ4D1O+Lk+HuVWygE5fItrCubTE605CBF/CUtsWAAAA',
  },
  {
    id: 'img-1479',
    kind: 'image',
    src: '/media/photos/img-1479.webp',
    width: 450,
    height: 600,
    orientation: 'portrait',
    blurDataUrl:
      'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADwAQCdASoJAAwAA4BaJYwC7AD0V0Lzm5QA99Ykm5BRM5mNQoE4o1yMjHEG1MLr9aqi0eVAKAp6/XWuIAA=',
  },
  {
    id: 'img-1484',
    kind: 'image',
    src: '/media/photos/img-1484.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACQAQCdASoMAAkAA4BaJZQAAbhu0kAA/pghTwwTXTi8DzBX6LQ4wArAfg5LhhrdzvjDuOak+X01YuIKkvsUy8PkrQAAAA==',
  },
  {
    id: 'bceeb212-6993-44ef-9966-eea63b306cc4',
    kind: 'image',
    src: '/media/photos/bceeb212-6993-44ef-9966-eea63b306cc4.webp',
    width: 450,
    height: 600,
    orientation: 'portrait',
    blurDataUrl:
      'data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAABwAQCdASoJAAwAA4BaJZwAAk/uWADMnKTc4yxHp07bTqh/elDWCqjSIuRraF0LxO/ml6B81gAAAA==',
  },
  {
    id: '7e9cf6f1-bf67-4cd1-ae08-1ca97711f35b',
    kind: 'image',
    src: '/media/photos/7e9cf6f1-bf67-4cd1-ae08-1ca97711f35b.webp',
    width: 450,
    height: 600,
    orientation: 'portrait',
    blurDataUrl:
      'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoJAAwAA4BaJZwAApy61mYAAM3dCo9/C19CX3HWAkgMy0EIXCHolozcuRaXn/POJLNCaikgAAA=',
  },
  {
    id: 'a6816173-c39d-4a76-8d7c-b76816696070',
    kind: 'image',
    src: '/media/photos/a6816173-c39d-4a76-8d7c-b76816696070.webp',
    width: 338,
    height: 600,
    orientation: 'portrait',
    blurDataUrl:
      'data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoHAAwAA4BaJaACdAD5jp+11dAA/sI2XYSWnCfV5L7OptTlmXSwBQNDi9GqVd2drAklsXuc4GIAAA==',
  },
  {
    id: '62e190ee-638b-4cc4-8307-dc54044596d6',
    kind: 'image',
    src: '/media/photos/62e190ee-638b-4cc4-8307-dc54044596d6.webp',
    width: 600,
    height: 338,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoMAAcAA4BaJZQAAlru1LYkAAD94lrhoFCsFgUa4Wm5ljU/nqRvo0OSmeHZg/rKq6v7uA+AAAA=',
  },
  {
    id: 'img-2044',
    kind: 'image',
    src: '/media/photos/img-2044.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACQAQCdASoMAAkAA4BaJQBOgBsW6wAA4fdan/gTtclHjqcF/jZb9O1WM1bHT6garT2R6SwZ2IIMHjhIxgTARJzYhEpT5ouYgAA=',
  },
  {
    id: 'img-2110',
    kind: 'image',
    src: '/media/photos/img-2110.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoMAAkAA4BaJQBOgCLKImQiPgAA/u0LI+vxPqTshh71UHf3Z63vx76gaUh3EvsUN1XoVfvfLZHzsKEPewAAAA==',
  },
  {
    id: 'img-2118',
    kind: 'image',
    src: '/media/photos/img-2118.webp',
    width: 450,
    height: 600,
    orientation: 'portrait',
    blurDataUrl:
      'data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoJAAwAA4BaJZACdAEXtiiDhYcgAPsdvMxF/vVEHejWc8tU/k0m2IQf+mzXnE+ym5lX26ZirvY9V8cmzmUoBZQ2CdgAAA==',
  },
  {
    id: 'img-2264',
    kind: 'image',
    src: '/media/photos/img-2264.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoMAAkAA4BaJYwCw7DdjZdXw39AAPz3k9cgYaitaIixSuxFvB+dn0SoW+HyNSqi5Y4htsnIA3WxKBfeF1C16vWwRgAAAA==',
  },
  {
    id: 'img-2312',
    kind: 'image',
    src: '/media/photos/img-2312.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAQAgCdASoMAAkAA4BaJYwCw7EPDElG41AAAPa3z4ZqUyk99uk7O97dTtBD5nrdmRUhWN5651B8ivcM9uxwJnoLFCAAAA==',
  },
  {
    id: '6ad5d647-3611-4873-9fcd-50465ef97b9e',
    kind: 'video',
    src: '/media/videos/6ad5d647-3611-4873-9fcd-50465ef97b9e.mp4',
    poster: '/media/videos/6ad5d647-3611-4873-9fcd-50465ef97b9e.webp',
    width: 848,
    height: 478,
    duration: 19,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACQAQCdASoMAAcAA4BaJZwAAkrMHAAA/ubUWHgTy0UWt3wLlwO3Q+HraZrtj0wl/ZkZqIQ/50ChQAAA',
  },
  {
    id: 'img-2374',
    kind: 'image',
    src: '/media/photos/img-2374.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACwAQCdASoMAAkAA4BaJZQAAt1hqzkAAP40c5/1l2yWzTuM7kMecKlaK9TUs0QOwgc4GvwXUHAAAA==',
  },
  {
    id: 'img-2373',
    kind: 'image',
    src: '/media/photos/img-2373.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoMAAkAA4BaJZwAAl3aUtUEUAD+lxBnHyLaQFLUX6j2dmW2CTh/oUKk9PshRNQ1n7RfAAAA',
  },
  {
    id: 'img-2382',
    kind: 'image',
    src: '/media/photos/img-2382.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAQAgCdASoMAAkAA4BaJZQAD4wQ6E5r0DXgAP4Iy26BjXQ8fYKGPolXhr+mhWkhTGUgbrzt63RF49N3l0hHzcqszroLQAAA',
  },
  {
    id: '490754b5-69ae-4ae0-a545-d0f714170e2d',
    kind: 'image',
    src: '/media/photos/490754b5-69ae-4ae0-a545-d0f714170e2d.webp',
    width: 600,
    height: 338,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAAAQAgCdASoMAAcAA4BaJYwCdAEVcGlZS2QAAPZg9HZCH8tWYQX1jVsS8KHKIwChOghxBZ1AybSz8wr3AAA=',
  },
  {
    id: 'df5fce9f-3232-4d2d-a1cc-c61f507de491',
    kind: 'image',
    src: '/media/photos/df5fce9f-3232-4d2d-a1cc-c61f507de491.webp',
    width: 600,
    height: 338,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoMAAcAA4BaJYwCdADhYOnO8AAA/uoAKrrwDDf2fGR84YzjyLIbgmBphSGp+//jlvjAOIAA',
  },
  {
    id: 'a6b5217c-219e-4090-9d77-68a82cbe85a5',
    kind: 'image',
    src: '/media/photos/a6b5217c-219e-4090-9d77-68a82cbe85a5.webp',
    width: 600,
    height: 338,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoMAAcAA4BaJYwCdADbWq5qYAAA/tYmGFJCUzJkY8BaB/uNzOuSq2W79LTWignns2XrIAAA',
  },
  {
    id: 'img-2387',
    kind: 'image',
    src: '/media/photos/img-2387.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAQCdASoMAAkAA4BaJZwAAmgoTGZoAAD+W+s2xiSkY+8HddhaKG0Yge4Bm4PbM70eLPTOqQXVNSE1AtFm66j5FdyE4rbWh3iAgAAA',
  },
  {
    id: 'img-2386',
    kind: 'image',
    src: '/media/photos/img-2386.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACwAQCdASoMAAkAA4BaJQAASuy5o2oAAP7XYZDY5vfBv0wUxnJChMUUVXbKw/T+AE/+cBuZM/3+e0JawtoGJnhphT2IxxvJxQI0EIgA',
  },
  {
    id: 'a0673548-59dd-42ca-9122-30a9bb45a3dc',
    kind: 'video',
    src: '/media/videos/a0673548-59dd-42ca-9122-30a9bb45a3dc.mp4',
    poster: '/media/videos/a0673548-59dd-42ca-9122-30a9bb45a3dc.webp',
    width: 720,
    height: 1280,
    duration: 47,
    orientation: 'portrait',
    blurDataUrl:
      'data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAQCdASoHAAwAA4BaJQBOgB8uqJ4AAAD2uP0F63lqbYi8jamfYJQJz1rkusmD4xrBaSnbeUBSewhs1oAAAA==',
  },
  {
    id: 'img-2414',
    kind: 'video',
    src: '/media/videos/img-2414.mp4',
    poster: '/media/videos/img-2414.webp',
    width: 1280,
    height: 720,
    duration: 11,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAQAgCdASoMAAcAA4BaJZQCw7EegjdQ/rAAAP6JfQTk9eN89v59l2qJwvGb2yym82krfDkhrT1SWxkTY1ByjwSV4gAAAA==',
  },
  {
    id: 'img-2434',
    kind: 'video',
    src: '/media/videos/img-2434.mp4',
    poster: '/media/videos/img-2434.webp',
    width: 720,
    height: 1280,
    duration: 29,
    orientation: 'portrait',
    blurDataUrl:
      'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoHAAwAA4BaJZQAAppVGNTAAPKXAc7b+5hUbSEAS1bp+veAQfZ4IW48mbRLBGHZDCAJscQIAAA=',
  },
  {
    id: 'img-2964',
    kind: 'image',
    src: '/media/photos/img-2964.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQAgCdASoMAAkAA4BaJZgCdAELYrJhJ0fAAPwz4qdzdxNhAQyJmX7RU+4jHlyMrh+MEujq/guyO1B5c2KmNn31sJp19NKVCEfeYtrQny9nwjisN5nMgAAA',
  },
  {
    id: 'img-2797',
    kind: 'image',
    src: '/media/photos/img-2797.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoMAAkAA4BaJbAC7AEf2fmXkAD+Cb1SMsrPAE4MpzBBzk3BW3qFSRDkBgMGtoNeNH39unUF/ewPZ8c1Hp9VAAAA',
  },
  {
    id: 'img-2798',
    kind: 'image',
    src: '/media/photos/img-2798.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAQCdASoMAAkAA4BaJQBOkERiafz4AAD9qJfXJLMsOUeQ0Y2zx2wt3IUzocRq7y57o9rPk4QFjRBWwzyv4QNp8Xvg0aZSzGjQWuwVYoly8ClMRKAAAA==',
  },
  {
    id: 'img-2968',
    kind: 'image',
    src: '/media/photos/img-2968.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoMAAkAA4BaJQBOgBu2k24EAAD84jdvHEQRKF0kUMJN7iX7B4NCePUX+BV5YcLlafT46HCtecyNK38EpY70S5OrbvKmRFsAAAA=',
  },
  {
    id: '2530172260126415111',
    kind: 'image',
    src: '/media/photos/2530172260126415111.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoMAAkAA4BaJZwAAxf+qYe/QAD+AacAIzjcuBXVn6q9UHrNuWYGyvJx5AAAAA==',
  },
  {
    id: '3914887227531153922',
    kind: 'image',
    src: '/media/photos/3914887227531153922.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACwAQCdASoMAAkAA4BaJZwAAmi2TBgAAP7yFpVr1LXteaIiMJ74AQDFiSvMyAODcvO/Ko8KXdQ4AA==',
  },
  {
    id: '8454996906743694765',
    kind: 'image',
    src: '/media/photos/8454996906743694765.webp',
    width: 338,
    height: 600,
    orientation: 'portrait',
    blurDataUrl:
      'data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoHAAwAA4BaJagC7AD0SC8pGCgA/anlDAQnwN9VVNX2vf893Lv8A217JhsI3qIUXDkdQKgtwHdtQ6AA',
  },
  {
    id: '833465387477952285',
    kind: 'video',
    src: '/media/videos/833465387477952285.mp4',
    poster: '/media/videos/833465387477952285.webp',
    width: 1280,
    height: 720,
    duration: 19,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoMAAcAA4BaJaQAAqr85QzqAAD+7RKFGZknEtiBkZx/KA08e3pZ3enILlI2UOigAAA=',
  },
  {
    id: '5453990239390041725',
    kind: 'video',
    src: '/media/videos/5453990239390041725.mp4',
    poster: '/media/videos/5453990239390041725.webp',
    width: 1280,
    height: 720,
    duration: 14,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADwAQCdASoMAAcAA4BaJZwAAxaliTLJggAA9HXYkwDyRGmuZal9yCP37txBHAsfaVPda6mBdQoAAA==',
  },
  {
    id: '2014366607164268207',
    kind: 'video',
    src: '/media/videos/2014366607164268207.mp4',
    poster: '/media/videos/2014366607164268207.webp',
    width: 1280,
    height: 720,
    duration: 15,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADwAQCdASoMAAcAA4BaJZQC7AD0vMXPZSAA/u8rG2RYRVfkOO7KK5Q7cT0MdMNUkam5vQYAAAA=',
  },
  {
    id: '1102936990649038933',
    kind: 'video',
    src: '/media/videos/1102936990649038933.mp4',
    poster: '/media/videos/1102936990649038933.webp',
    width: 1280,
    height: 720,
    duration: 2,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoMAAcAA4BaJaQAAxYUAWAg4AD5DrVO/dnOs5Nl0yW7Mv/h8n4VeAAA',
  },
  {
    id: '2195008587047542519',
    kind: 'video',
    src: '/media/videos/2195008587047542519.mp4',
    poster: '/media/videos/2195008587047542519.webp',
    width: 1280,
    height: 720,
    duration: 21,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoMAAcAA4BaJaQAAutK/xQaAADLSkKF4qUVVyTM8dGh3R5KYLPkxR0K167zdwVZF6wAAAAA',
  },
  {
    id: '1390147046224996442',
    kind: 'video',
    src: '/media/videos/1390147046224996442.mp4',
    poster: '/media/videos/1390147046224996442.webp',
    width: 1280,
    height: 720,
    duration: 18,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAAAwAgCdASoMAAcAA4BaJZwC7AEfp09WU3MSAAD+TZVdAr0FgGz2HtmaXw+ZMW9nvjNC/NUKwBAAAA==',
  },
  {
    id: '4039484844690051570',
    kind: 'video',
    src: '/media/videos/4039484844690051570.mp4',
    poster: '/media/videos/4039484844690051570.webp',
    width: 1280,
    height: 720,
    duration: 16,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADwAQCdASoMAAcAA4BaJZwAAxdB7wzmiWAAzKKh98RDptgzI/a/um9sVuMIZ2xxBTcAAA==',
  },
  {
    id: '718490688518547100',
    kind: 'image',
    src: '/media/photos/718490688518547100.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoMAAkAA4BaJZwAAp1zXmN44AAA/my+nmIFJ8l7+uEDCAmCxQn4nJxAyFoqGNUp1la8/uBCChjuXgAA',
  },
  {
    id: '9173955381485114153',
    kind: 'image',
    src: '/media/photos/9173955381485114153.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAQCdASoMAAkAA4BaJZwC7ADdK5YnAAD9tquZDb2FWQSzf27o+FIaOYqUWSGjvdWxtL2/SuIlfXhh9yAAAA==',
  },
  {
    id: '7263495715122942951',
    kind: 'image',
    src: '/media/photos/7263495715122942951.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACQAQCdASoMAAkAA4BaJZwAAkrANgAA/sGHtU5hg62tbl9pXEblohyETmcZG1azsDpiRZQNgi6EuPA4AAA=',
  },
  {
    id: '7263495715122942951-jpg-1',
    kind: 'image',
    src: '/media/photos/7263495715122942951-jpg-1.webp',
    width: 1920,
    height: 1440,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACQAQCdASoMAAkAA4BaJZwAAlRrOQgA/sGHtU5hg6FEzg+W9NMy23FMin1nfyoC9DDy/i4YiWYIoAAA',
  },
  {
    id: '7370407339484804058',
    kind: 'image',
    src: '/media/photos/7370407339484804058.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACQAQCdASoMAAkAA4BaJZwAAlKBTYAA/ktYh931b6vrnRd/mFRiwFzZ+1xBeH7t4BJO9e3vExFkHt4Lpk4SmAAA',
  },
  {
    id: '7708165599640676557',
    kind: 'image',
    src: '/media/photos/7708165599640676557.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACQAQCdASoMAAkAA4BaJQAAS1u7SQAA99CihlcwyMTYVtyD2FOsfndHjDACNLNs2wEL0fMlG6TkuxieOhUBt+io9RPQmwAA',
  },
  {
    id: '1976410277356390327',
    kind: 'image',
    src: '/media/photos/1976410277356390327.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAQCdASoMAAkAA4BaJZwAAmf3O6zAAP5mHpGedZCSakulB4Xhf1Tv5lP/v3iSU4MWEoAAAAA=',
  },
  {
    id: '955498783347505657',
    kind: 'image',
    src: '/media/photos/955498783347505657.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACQAQCdASoMAAkAA4BaJZQAAldi5MAA/rD2I9Reuc5p6NaTaUx5OXRUYu8Jry8mbFLRWbKtfdsEjmhfh3tfewcQAAA=',
  },
  {
    id: '7306127883356801794',
    kind: 'image',
    src: '/media/photos/7306127883356801794.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACQAQCdASoMAAkAA4BaJQAASvFfinAA4TWpXy+Pc+Wy843Idk32VyNE50/M4K9BidruU/8cVkkprn6S/yt7sIzv30jG+nbWwAA=',
  },
  {
    id: '4598324176699077351',
    kind: 'image',
    src: '/media/photos/4598324176699077351.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoMAAkAA4BaJZwAA2x51Xcq4AD+8a/6c95EbmAdISzHw3lfBwuSzABtjA9EgvvBFkAAAA==',
  },
  {
    id: '3511554821892522494',
    kind: 'image',
    src: '/media/photos/3511554821892522494.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoMAAkAA4BaJZwAAhWMrpNgAP6sa7/F20BXMgxfHCRnJRblPlZXI/bjH3AZQ9xyumFnNX2ZZR9bAAAA',
  },
  {
    id: '1694422870994021925',
    kind: 'image',
    src: '/media/photos/1694422870994021925.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoMAAkAA4BaJZwAAxOgdXLJyAAA/sB7w9sRz6GVkbuxmEZXjOP+NG29XwysbkqjziYwAAAA',
  },
  {
    id: '3531799507795455560',
    kind: 'image',
    src: '/media/photos/3531799507795455560.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoMAAkAA4BaJZwAAlr5QFSQAP7XP16w5ujp9naKA1sef8LvNrVXmucz40AsQf8LiY6WdH7OyXvjAAAA',
  },
  {
    id: '4349539558343909612',
    kind: 'image',
    src: '/media/photos/4349539558343909612.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoMAAkAA4BaJZwAAsfr1tJMAAD9cA90Tj7IOsGl0FHCJynxXRJsl9ovHYlwthGq7pmwC31fssmB3E5rQUAAAA==',
  },
  {
    id: '2385689756380270605',
    kind: 'image',
    src: '/media/photos/2385689756380270605.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACwAQCdASoMAAkAA4BaJZwAApgNhUbAAOJ+ZuMlNjof0bomnGf7ZRS3/DqtIbscAIaxXFLCvo7nGv2sqYsawLuZeAA=',
  },
  {
    id: '941607886375482599',
    kind: 'image',
    src: '/media/photos/941607886375482599.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAAAwAgCdASoMAAkAA4BaJZQC7AEfoBc6M5GUAAD8J+GebGIrNOs/QhHMVKEJ49oZWZSpSlMNUaygAA==',
  },
  {
    id: '8404362930630178800',
    kind: 'image',
    src: '/media/photos/8404362930630178800.webp',
    width: 600,
    height: 450,
    orientation: 'landscape',
    blurDataUrl:
      'data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoMAAkAA4BaJZwCsADdLOjzRwAA/AEwroxWhl0SNVpjGrrfz/pYHCGBCoqxkeUtjIPQK0SINxX93pGKnBtgUTQORBRAAA==',
  },
];
